version: '3.9'

services:
  nothingtoseehere:
    image: "vallezw/nothingtoseehere"
    container_name: nothingtoseehere
    restart: unless-stopped
    networks:
      - infra-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-router.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-router.priority=1"
      - "traefik.http.routers.error-router.entrypoints=websecure"
      - "traefik.http.routers.error-router.middlewares=nothingtoseehere"
      - "traefik.http.middlewares.nothingtoseehere.errors.status=400-599"
      - "traefik.http.middlewares.nothingtoseehere.errors.service=error-pages-service"
      - "traefik.http.middlewares.nothingtoseehere.errors.query=/index.html"
      - "traefik.http.services.error-pages-service.loadbalancer.server.port=80"

networks:
  infra-network:
    external: true
    name: infra-network
