version: '3.9'

services:
  vscode:
    image: "linuxserver/code-server"
    container_name: code-server
    restart: unless-stopped
    environment:
      - PASSWORD={{ vscode.password }}
      - SUDO_PASSWORD={{ vscode.password }}
    networks:
      - infra-network
    volumes:
      - "${APPDATA_PATH}/code-server:/app/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.vscode.loadbalancer.server.port=8443"
      - "traefik.http.routers.vscode.rule=Host(`code.${BASE_URL}`)"
      - "traefik.http.routers.vscode.entrypoints=websecure"
      - "traefik.http.routers.vscode.tls=true"
      - "traefik.http.routers.vscode.tls.certresolver=leresolver"

networks:
  infra-network:
    external: true
    name: infra-network
