version: '3.9'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - "${APPDATA_PATH}/registry/data:/var/lib/registry"
      - "${APPDATA_PATH}/registry/auth:/auth"
    networks:
      - infra-network
    environment:
      - REGISTRY_HTTP_SECRET=my_registry_secret
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
  
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    environment:
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Pavel's Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on: ['registry']
    networks:
      - infra-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.rule=Host(`registry.${BASE_URL}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"
      - "traefik.frontend.auth.basic=..."
      - "traefik.frontend.passHostHeader=true"

networks:
  infra-network:
    external: true
    name: infra-network
