version: '3.9'

services:
  portainer:
    image: "portainer/portainer-ce"
    container_name: portainer
    restart: unless-stopped
    networks:
      - infra-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${APPDATA_PATH}/portainer-ce:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${BASE_URL}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"

networks:
  infra-network:
    external: true
    name: infra-network
