- name: Clean render path.
  ansible.builtin.file:
    state: absent
    dest: '{{ render_path }}'
  changed_when: false

- name: Create neccessary directories.
  ansible.builtin.file:
    state: directory
    dest: '{{ render_path }}/{{ item.path }}'
    mode: 0755
  changed_when: false
  with_filetree: '{{ docker_compose_dir }}'
  when: item.state == 'directory'

- name: Render templated files.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ render_path }}/{{ item.path }}"
    force: true
    mode: 0644
  changed_when: false
  with_filetree: '{{ docker_compose_dir }}'
  when: item.state == 'file' and item.path not in render_blacklist

- name: Copy blacklisted files.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ render_path }}/{{ item.path }}"
    force: true
    mode: 0644
  changed_when: false
  with_filetree: '{{ docker_compose_dir }}'
  when: item.state == 'file' and item.path in render_blacklist
