version: '3.9'

services:
  broker:
    image: docker.io/library/redis:6.0
    restart: unless-stopped
    networks:
      - infra-network
    volumes:
      - ${APPDATA_PATH}/paperless-ngx/redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    depends_on:
      - broker
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    environment:
      - PAPERLESS_URL=https://paperless.${BASE_URL}
      - PAPERLESS_SECRET_KEY=...
      - PAPERLESS_TIME_ZONE=Europe/Berlin
      - PAPERLESS_OCR_LANGUAGE=deu
      - "PAPERLESS_OCR_LANGUAGES=eng deu"
      - PAPERLESS_REDIS=redis://broker:6379
    volumes:
      - ${APPDATA_PATH}/paperless-ngx/data:/usr/src/paperless/data
      - ${APPDATA_PATH}/paperless-ngx/media:/usr/src/paperless/media
      - ${APPDATA_PATH}/paperless-ngx/export:/usr/src/paperless/export
      - ${APPDATA_PATH}/paperless-ngx/consume:/usr/src/paperless/consume
    networks:
      - infra-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.paperless-ngx.loadbalancer.server.port=8000"
      - "traefik.http.routers.paperless-ngx.rule=Host(`paperless.${BASE_URL}`)"
      - "traefik.http.routers.paperless-ngx.entrypoints=websecure"
      - "traefik.http.routers.paperless-ngx.tls=true"
      - "traefik.http.routers.paperless-ngx.tls.certresolver=leresolver"

networks:
  infra-network:
    external: true
    name: infra-network
