version: '3.9'

services:
  rstudio:
    image: "rocker/rstudio"
    container_name: rstudio
    restart: unless-stopped
    environment:
      - USER=.
      - PASSWORD=.
    networks:
      - infra-network
    volumes:
      - "${APPDATA_PATH}/rstudio:/home/pavel"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.rstudio.loadbalancer.server.port=8787"
      - "traefik.http.routers.rstudio.rule=Host(`rstudio.${BASE_URL}`)"
      - "traefik.http.routers.rstudio.entrypoints=websecure"
      - "traefik.http.routers.rstudio.tls=true"
      - "traefik.http.routers.rstudio.tls.certresolver=leresolver"

networks:
  infra-network:
    external: true
    name: infra-network
