version: '3.9'

services:
  nothingtoseehere:
    image: "vallezw/nothingtoseehere"
    container_name: nothingtoseehere
    restart: unless-stopped
    networks:
      - infra-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nothingtoseehere.loadbalancer.server.port=80"
      - "traefik.http.routers.nothingtoseehere.rule=Host(`${BASE_URL}`)"
      - "traefik.http.routers.nothingtoseehere.entrypoints=websecure"
      - "traefik.http.routers.nothingtoseehere.tls=true"
      - "traefik.http.routers.nothingtoseehere.tls.certresolver=leresolver"

networks:
  infra-network:
    external: true
    name: infra-network
