version: '3.9'

services:
  registry-valentin:
    image: registry:2
    container_name: registry-valentin
    restart: always
    volumes:
      - "${APPDATA_PATH}/registry/data:/var/lib/registry"
      - "${APPDATA_PATH}/registry/auth:/auth"
    networks:
      - infra-network
    environment:
      - REGISTRY_HTTP_SECRET=my_registry_secret
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui-valentin
    restart: always
    environment:
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Valentin's Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry-valentin:5000
      - SINGLE_REGISTRY=true
    depends_on: ['registry-valentin']
    networks:
      - infra-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.registry-ui-valentin.loadbalancer.server.port=80"
      - "traefik.http.routers.registry-ui-valentin.rule=Host(`registry-valentin.${BASE_URL}`)"
      - "traefik.http.routers.registry-ui-valentin.entrypoints=websecure"
      - "traefik.http.routers.registry-ui-valentin.tls=true"
      - "traefik.http.routers.registry-ui-valentin.tls.certresolver=leresolver"
      - "traefik.registry-ui-valentin.auth.basic={{ registry_valentin.basicauth }}"
      - "traefik.registry-ui-valentin.passHostHeader=true"

networks:
  infra-network:
    external: true
    name: infra-network
