version: '3.9'

services:
  valentin-blog:
    image: "ghost"
    container_name: valentin-blog
    restart: unless-stopped
    environment:
      - url=https://valentin.${BASE_URL}
    networks:
      - infra-network
    volumes:
      - "${APPDATA_PATH}/valentin-blog:/var/lib/ghost/content"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.valentin-blog.loadbalancer.server.port=2368"
      - "traefik.http.routers.valentin-blog.rule=Host(`valentin.${BASE_URL}`)"
      - "traefik.http.routers.valentin-blog.entrypoints=websecure"
      - "traefik.http.routers.valentin-blog.tls=true"
      - "traefik.http.routers.valentin-blog.tls.certresolver=leresolver"

networks:
  infra-network:
    external: true
    name: infra-network
